### ISSUE TITLE
history section not completed

### ISSUE THREAD

**Issue by AkuSarma** [AkuSarma/Calculator#1]
a section which shows all the previous calculations done

**Comment by PritKalariya** [comment]
Can you please specify, what type of history do you want?

**Comment by AkuSarma** [comment]
I just want to track all the calculations done and store them and show them in this tab
<br>
<br>
![image](https://user-images.githubusercontent.com/68861875/136002411-0a2a27e1-ea0a-4617-9197-622c48f3559a.png)

**Comment by PritKalariya** [comment]
Ohk! How about creating a different file that tracks the history, and display it in the H tab? We we want to display the history we can delete the file.

**Comment by AkuSarma** [comment]
Ok but can you suggest with what we can display it on the h tab

**Comment by PritKalariya** [comment]
I haven't worked with kivi module. 

I guess we'll have to figure out a way to read and display from the file.

**Comment by AkuSarma** [comment]
ok
